/**
 * Device Module Type Definitions
 * These interfaces are designed for frontend consumption
 * Includes _id fields for MongoDB documents
 */

// 🔹 Calibration Interface

export type Endianness = "ABCD" | "CDAB" | "BADC" | "DCBA" | "NONE";

export type DeviceStatus = "online" | "offline" | "maintenance";
export interface ICalibration {
  scaling: number;
  offset: number;
}

// 🔹 Threshold Interface
export interface IThreshold {
  min?: number;
  max?: number;
  message?: string;
}

// 🔹 Modbus Read Interface
export interface IModbusRead {
  readId: string; // Auto-generated by backend
  slaveId: string; // Reference to parent slave
  portKey: string; // Virtual port
  registerType?: "holding" | "input" | "coil" | "discrete";
  functionCode: "fc_1" | "fc_2" | "fc_3" | "fc_4";
  // fc_1: Read Coils (registerType: coil)
  // fc_2: Read Discrete Inputs (registerType: discrete)
  // fc_3: Read Holding Registers (registerType: holding)
  // fc_4: Read Input Registers (registerType: input)
  startAddress: number;
  bitsToRead: number;
  name: string;
  description?: string;
  scaling?: number;
  offset?: number;
  unit?: string;
  tag?: string;
  dataType?: string;
  endianness?: Endianness;
}

// 🔹 Serial Configuration Interface
export interface ISerialConfig {
  baudRate: number;
  dataBits: number;
  stopBits: number;
  parity: "none" | "even" | "odd";
}

// 🔹 Polling Configuration Interface
export interface IPollingConfig {
  intervalMs: number;
  timeoutMs: number;
  retries: number;
}

// 🔹 Modbus Slave Interface
export interface IModbusSlave {
  slaveId: string; // Auto-generated by backend
  portKey: string; // Reference to parent port (from DeviceModel)
  name: string;
  serial: ISerialConfig;
  polling: IPollingConfig;
  reads: IModbusRead[];
}

// 🔹 Port Interface
export interface IPort {
  portKey: string;
  name: string;
  portType: string; // ObjectId as string
  unit?: string;
  calibrationValue?: ICalibration;
  status?: string; // From PORT_STATUS enum
  thresholds?: IThreshold;
  modbusSlaves?: IModbusSlave[]; // Only used for Modbus ports
}

// 🔹 Location Interface
export interface ILocation {
  lat?: number;
  lng?: number;
  address?: string;
}

// 🔹 Main Device Interface
export interface IDevice {
  _id?: string;
  configId: string;
  name: string;
  imei: string;
  deviceModelId: { _id: string; name: string }; // populated
  organizationId?: { _id: string; name: string }; // populated optional
  status: DeviceStatus;
  location?: ILocation;
  metadata?: Record<string, string | number | boolean | null>;
  ports: IPort[];
  pointOfContact?: string;
  alertEmails?: string[];
  alertPhones?: string[];
  assignedAt?: string;
  lastSeen?: string;
  manufacturingYear?: string;
  createdAt?: string;
  updatedAt?: string;
}

// 🔹 Device Creation Input (without _id and timestamps)
export interface IDeviceCreateInput {
  name: string;
  imei: string;
  deviceModelId: string;
  metadata?: Record<string, string | number | boolean | null>;
  manufacturingYear?: string;
}

// 🔹 Device Update Input (all fields optional except _id)
export interface IDeviceUpdateInput {
  configId?: string;
  name?: string;
  organizationId?: string;
  status?: DeviceStatus;
  location?: ILocation;
  metadata?: Record<string, string | number | boolean | null>;
  ports?: IPort[];
  pointOfContact?: string;
  alertEmails?: string[];
  alertPhones?: string[];
  assignedAt?: string;
}

// 🔹 Port Creation Input (without _id)
export interface IPortCreateInput {
  portKey: string;
  name: string;
  portType: string;
  unit?: string;
  calibrationValue?: ICalibration;
  status?: string;
  thresholds?: IThreshold;
  modbusSlaves?: IModbusSlave[];
}

// 🔹 Modbus Slave Creation Input (without _id)
export interface IModbusSlaveCreateInput {
  name: string;
  serial: ISerialConfig;
  polling: IPollingConfig;
  reads: IModbusRead[];
}

// 🔹 Response wrapper for paginated device list
export interface IDeviceListResponse {
  data: IDevice[];
  total: number;
  page: number;
  limit: number;
}

// 🔹 Response wrapper for single device
export interface IDeviceResponse {
  data: IDevice;
  message?: string;
}

export enum FUNCTION_CODE {
  fc_1 = "fc_1",
  fc_2 = "fc_2",
  fc_3 = "fc_3",
  fc_4 = "fc_4",
}

export const FUNCTION_CODE_OPTIONS = [
  { label: "Read Coils (FC 1)", value: FUNCTION_CODE.fc_1 },
  { label: "Read Discrete Inputs (FC 2)", value: FUNCTION_CODE.fc_2 },
  { label: "Read Holding Registers (FC 3)", value: FUNCTION_CODE.fc_3 },
  { label: "Read Input Registers (FC 4)", value: FUNCTION_CODE.fc_4 },
];

export const BITS_TO_READ_OPTIONS = [
  { label: "8", value: "8" },
  { label: "16", value: "16" },
  { label: "32", value: "32" },
  { label: "64", value: "64" },
];

export const PORT_STATUS_OPTIONS = [
  { label: "ACTIVE", value: "ACTIVE" },
  { label: "INACTIVE", value: "INACTIVE" },
];

export const BAUD_RATE_OPTIONS = [
  { label: "2400", value: 2400 },
  { label: "4800", value: 4800 },
  { label: "9600", value: 9600 },
  { label: "19200", value: 19200 },
  { label: "38400", value: 38400 },
  { label: "57600", value: 57600 },
  { label: "115200", value: 115200 },
];

export const DATA_BITS_OPTIONS = [
  { label: "7", value: 7 },
  { label: "8", value: 8 },
];

export const STOP_BITS_OPTIONS = [
  { label: "1", value: 1 },
  { label: "2", value: 2 },
];

export const PARITY_OPTIONS = [
  { label: "None", value: "none" },
  { label: "Even", value: "even" },
  { label: "Odd", value: "odd" },
];

export const ENDIANNESS_OPTION = [
  { label: "ABCD", value: "ABCD" as const },
  { label: "CDAB", value: "CDAB" as const },
  { label: "BADC", value: "BADC" as const },
  { label: "DCBA", value: "DCBA" as const },
  { label: "NONE", value: "NONE" as const },
];

export const DEVICE_STATUS_OPTIONS = [
  { label: "Online", value: "online" },
  { label: "Offline", value: "offline" },
  { label: "Maintenance", value: "maintenance" },
];
