/**
 * Device Module Type Definitions
 * These interfaces are designed for frontend consumption
 * Includes _id fields for MongoDB documents
 */

// 🔹 Calibration Interface
export interface ICalibration {
  scaling: number;
  offset: number;
}

// 🔹 Threshold Interface
export interface IThreshold {
  min?: number;
  max?: number;
  message?: string;
}

// 🔹 Modbus Read Interface
export interface IModbusRead {
  readId: string; // Auto-generated by backend
  slaveId: string; // Reference to parent slave
  portKey: string; // Virtual port
  registerType?: "holding" | "input" | "coil" | "discrete";
  functionCode: "fc_1" | "fc_2" | "fc_3" | "fc_4";
  // fc_1: Read Coils (registerType: coil)
  // fc_2: Read Discrete Inputs (registerType: discrete)
  // fc_3: Read Holding Registers (registerType: holding)
  // fc_4: Read Input Registers (registerType: input)
  startAddress: number;
  bitsToRead: number;
  name: string;
  description?: string;
  scaling?: number;
  offset?: number;
  unit?: string;
  tag?: string;
  dataType?: string;
  endianness?: "ABCD " | "CDAB " | "BADC " | "DCBA" | "NONE";
}

// 🔹 Serial Configuration Interface
export interface ISerialConfig {
  baudRate: number;
  dataBits: number;
  stopBits: number;
  parity: "none" | "even" | "odd";
}

// 🔹 Polling Configuration Interface
export interface IPollingConfig {
  intervalMs: number;
  timeoutMs: number;
  retries: number;
}

// 🔹 Modbus Slave Interface
export interface IModbusSlave {
  slaveId: string; // Auto-generated by backend
  portKey: string; // Reference to parent port (from DeviceModel)
  name: string;
  serial: ISerialConfig;
  polling: IPollingConfig;
  reads: IModbusRead[];
}

// 🔹 Port Interface
export interface IPort {
  portKey: string;
  name: string;
  portType: string; // ObjectId as string
  unit?: string;
  calibrationValue?: ICalibration;
  status?: string; // From PORT_STATUS enum
  thresholds?: IThreshold;
  modbusSlaves?: IModbusSlave[]; // Only used for Modbus ports
}

// 🔹 Location Interface
export interface ILocation {
  lat?: number;
  lng?: number;
  address?: string;
}

// 🔹 Main Device Interface
export interface IDevice {
  _id?: string;
  configId: string;
  name: string;
  imei: string;
  deviceModelId: { _id: string; name: string }; // populated
  organizationId?: { _id: string; name: string }; // populated optional
  status: "online" | "offline" | "maintenance";
  location?: ILocation;
  metadata?: Record<string, string | number | boolean | null>;
  ports: IPort[];
  pointOfContact?: string;
  alertEmails?: string[];
  alertPhones?: string[];
  assignedAt?: Date;
  lastSeen?: Date;
  manufacturingYear?: Date;
  createdAt?: Date;
  updatedAt?: Date;
}

// 🔹 Device Creation Input (without _id and timestamps)
export interface IDeviceCreateInput {
  name: string;
  imei: string;
  deviceModelId: string;
  metadata?: Record<string, string | number | boolean | null>;
  manufacturingYear?: Date;
}

// 🔹 Device Update Input (all fields optional except _id)
export interface IDeviceUpdateInput {
  configId?: string;
  name?: string;
  organizationId?: string;
  status?: "online" | "offline" | "maintenance";
  location?: ILocation;
  metadata?: Record<string, string | number | boolean | null>;
  ports?: IPort[];
  pointOfContact?: string;
  alertEmails?: string[];
  alertPhones?: string[];
  assignedAt?: Date;
}

// 🔹 Port Creation Input (without _id)
export interface IPortCreateInput {
  portKey: string;
  name: string;
  portType: string;
  unit?: string;
  calibrationValue?: ICalibration;
  status?: string;
  thresholds?: IThreshold;
  modbusSlaves?: IModbusSlave[];
}

// 🔹 Modbus Slave Creation Input (without _id)
export interface IModbusSlaveCreateInput {
  name: string;
  serial: ISerialConfig;
  polling: IPollingConfig;
  reads: IModbusRead[];
}

// 🔹 Response wrapper for paginated device list
export interface IDeviceListResponse {
  data: IDevice[];
  total: number;
  page: number;
  limit: number;
}

// 🔹 Response wrapper for single device
export interface IDeviceResponse {
  data: IDevice;
  message?: string;
}
